### PR TITLE
fix large font sizes in Mirador table of contents from being inherite…

### LINKED ISSUE #60: CSS is beefing up font sizes and Mirador does not override them.
See the table of contents.

### PR DESCRIPTION
**Pull request by aeschylus**
…d from above. Closes #60.

### CODE REVIEW

File: db/schema.rb [hunk 1]
```diff
@@ -17,8 +17,8 @@
     t.integer  "user_id"
     t.datetime "created_at",                   null: false
     t.datetime "updated_at",                   null: false
-    t.text     "description"
     t.integer  "workspaces_count", default: 0
+    t.text     "description"
```
Comment (versae) [inline db/schema.rb]: Why the change in order? 🤔

Comment (aeschylus) [inline db/schema.rb]: Not sure. I didn't directly edit this file, though I did pull from master and run the migrations.

**Comment by aeschylus** [comment]
@versae Updating the branch fixed the weird schema ordering.
